apiVersion: v1
kind: Service
metadata:
  name: templates-database-${ENV_NAME}
  labels:
    app: templates-database-${ENV_NAME}
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: templates-database-${ENV_NAME}
