apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    app: templates_database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi