apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: templates-database-${ENV_NAME}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: templates-database-${ENV_NAME}
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: templates-database-config-${ENV_NAME}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: templates-database-secret-${ENV_NAME}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: templates-database-secret-${ENV_NAME}
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/
              name: templates-database-${ENV_NAME}
      volumes:
        - name: templates-database-${ENV_NAME}
          persistentVolumeClaim:
            claimName: postgres-pv-claim-${ENV_NAME}