apiVersion: v1
kind: ConfigMap
metadata:
  name: templates_database-config
  labels: 
    app: templates_database
data:
  POSTGRES_DB: templates_database
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres