apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim-${ENV_NAME}
  labels:
    app: templates-database-${ENV_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi