apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ${MICROSERVICE_NAME}
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: templates
  template:
    metadata:
      labels:
        app: templates
    spec:
      containers:
        - name: ${MICROSERVICE_NAME}
          image: habibullinilya/${IMAGE_NAME}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: ${MICROSERVICE_NAME}-configs
          readinessProbe: 
            httpGet: 
              path: /template/info/1
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 5
