apiVersion: v1
kind: Service
metadata:
  name: templates-microservice-${ENV_NAME}
  labels:
    app: templates-microservice-${ENV_NAME}
spec:
  type: NodePort
  ports:
   - port: 8080
  selector:
   app: templates-microservice-${ENV_NAME}