apiVersion: v1
kind: ConfigMap
metadata:
  name: templates_microservice-config
  labels: 
    app: templates_microservice
data:
  #database ip will be name of service in k8s
  DATABASE_INTERNAL_IP: templates_database
  DATABASE_INTERNAL_PORT: "5432"
  DATABASE_NAME: templates_database
