apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: templates-microservice-ingress-${ENV_NAME}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "microservice-static-ip"
spec:
  backend:
    serviceName: templates-microservice-${ENV_NAME}
    servicePort: 8080