apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${MICROSERVICE_NAME}-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "microservice-static-ip"
spec:
  backend:
    serviceName: ${MICROSERVICE_NAME}
    servicePort: 8080