apiVersion: v1
kind: Service
metadata:
  name: ${MICROSERVICE_NAME}
  labels:
    app: ${MICROSERVICE_NAME}
spec:
  type: NodePort
  ports:
   - port: 8080
     nodePort: 30081
  selector:
   app: ${MICROSERVICE_NAME}