apiVersion: v1
kind: ConfigMap
metadata:
  name: ${MICROSERVICE_NAME}-config
  labels: 
    app: ${MICROSERVICE_NAME}
data:
  #database ip will be name of service in k8s
  DATABASE_INTERNAL_IP: ${DATABASE_NAME}
  DATABASE_INTERNAL_PORT: "5432"
  DATABASE_NAME: ${DATABASE_NAME}
