apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-microservice-config-${ENV_NAME}
  labels: 
    app: templates-microservice-${ENV_NAME}
data:
  #database ip will be name of service in k8s
  DATABASE_INTERNAL_IP: templatess-database-${ENV_NAME}
  DATABASE_INTERNAL_PORT: "5432"
  DATABASE_NAME: templates-database-${ENV_NAME}
