apiVersion: apps/v1
kind: Deployment
metadata: 
  name: templates
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: templates
  template:
    metadata:
      labels:
        app: templates
    spec:
      containers:
        - name: templates
          image: habibullinilya/template_text_engine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: templates-config
          readinessProbe: 
            httpGet: 
              path: /template/info/1
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 3
            timeoutSeconds: 5
            successThreshold: 5
